# Generated by Django 4.0.2 on 2022-12-20 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0004_alter_reviewrating_user_alter_reviewrating_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='Catering_service',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='Overall_rating',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='Quality_of_service',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='Response_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='Total_reviews',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(default=343, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
        ),
    ]
