# Generated by Django 4.0.2 on 2022-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_venue_catering_service_venue_overall_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='Total_reviews',
            field=models.IntegerField(default='4'),
        ),
    ]
