# Generated by Django 4.0.2 on 2022-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_alter_venue_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='open_time',
            field=models.CharField(default='24', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
