# Generated by Django 4.0.2 on 2022-12-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_venue_open_time_alter_venue_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='type_of_hall',
            field=models.CharField(choices=[('Banquet Hall', 'Banquet Hall'), ('Function Hall', 'Function Hall'), ('Function / Banquet Hall', 'Function /Banquet Hall')], max_length=255),
        ),
    ]
