# Generated by Django 4.0.2 on 2022-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_title', models.CharField(max_length=25)),
                ('Title', models.CharField(max_length=300)),
                ('pincode', models.IntegerField(default='413501')),
                ('city', models.CharField(default='Dharashiv', max_length=10)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=400)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('photograph', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('facebook_link', models.URLField(default='')),
                ('twiter_link', models.URLField(default='')),
                ('instagram_link', models.URLField(default='')),
                ('linkdin_link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('couple_name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
